version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: portal
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portal
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  web:
    build: ../..
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../..:/app
    env_file:
      - ./env.dev
    ports: ["8000:8000"]
    depends_on: [db, redis]
  worker:
    build: ../..
    command: celery -A config worker -l info
    volumes:
      - ../..:/app
    env_file:
      - ./env.dev
    depends_on: [redis, web]
  beat:
    build: ../..
    command: celery -A config beat -l info
    volumes:
      - ../..:/app
    env_file:
      - ./env.dev
    depends_on: [redis, web]
volumes:
  pgdata:
